services:
  - type: web
    name: n8n
    env: docker
    # This tells Render to use the official, latest n8n image
    image:
      url: n8nio/n8n:latest
    region: oregon
    plan: standard # Or starter, depending on your plan
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: postgresdb
      # This group connects to your NEW database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db-new
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db-new
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db-new
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db-new
          property: password
      # This group sets up n8n's web address and security
      - key: WEBHOOK_URL
        value: https://n8n-526m.onrender.com
      - key: N8N_ENCRYPTION_KEY
        value: PAL8F#r9G,W*qJuU.3J.CNj7gLm!JadG
      - key: N8N_TRUST_PROXY
        value: true
      # General settings
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
      - key: TZ
        value: America/Sao_Paulo
      - key: N8N_LOG_LEVEL
        value: debug
      # Pruning settings (you can keep these as they are)
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: 168
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1

databases:
  - name: n8n-db-new
    plan: free # Use 'free' for the new database plan
